### PR TITLE
Fix a typo in duckdb sql client

### PR DESCRIPTION
**Pull request by yanghua**
`redshift` -> `duckdb`

### CODE REVIEW

**Comment by tlento** [comment]
Hi @yanghua ! Thanks for the patch. Before I approve and merge, could you please sign our CLA? The way we track this for now is via manual commentary on the PR, just add a comment like "I have read the CLA Document and I hereby sign the CLA" and that'll be good enough for us.

CLA: https://github.com/transform-data/metricflow/blob/main/TransformCLA.md

Thanks again!

**Comment by yanghua** [comment]
> Hi @yanghua ! Thanks for the patch. Before I approve and merge, could you please sign our CLA? The way we track this for now is via manual commentary on the PR, just add a comment like "I have read the CLA Document and I hereby sign the CLA" and that'll be good enough for us.
> 
> CLA: https://github.com/transform-data/metricflow/blob/main/TransformCLA.md
> 
> Thanks again!

I have read the CLA Document and I hereby sign the CLA.

**Comment by yanghua** [comment]
Hi @tlento BTW, should the signature be for every PR? Or only the first PR?

**Comment by tlento** [comment]
> Hi @tlento BTW, should the signature be for every PR? Or only the first PR?

As far as I know only the first one, but if we ever change the CLA we'll have to ask people to do it again.

**Review by tlento — APPROVED** [review]

**Pull request merged**
